# author: elliot-huffman
name: release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: none
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - name: Debug Env Variables (Safe)
        run: echo "NODE_AUTH_TOKEN length: ${#NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Publish to NPM
        run: npm run package:latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
