name: Version Bump

on:
  push:
    branches:
      - main
    paths:
      - "src/api/structures/**"
      - "src/controllers/**"
      - "src/executable/**"
      - "package.json"

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Secrets to Env
        run: |
          rm .env
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Root Install
        run: npm install

      - name: Build
        working-directory: website
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./website/out
          
      - name: Checkout repository for versioning
        uses: actions/checkout@v2
        with:
          branch: main

      - name: Bump version
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "GitHub Actions"
          git pull
          npm version patch -m "Bump version to %s [skip ci]"
          git push --set-upstream origin main --follow-tags
