name: Version Bump

on:
  push:
    branches:
      - main
    paths:
      - 'src/api/structures/**'
      - 'src/controllers/**'

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Bump version
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push --follow-tags
